version: '3.8'

services:
  php:
    image: php:8.3-fpm
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - ${VITE_PORT:-5174}:${VITE_PORT:-5174}
    volumes:
      - ./:/var/www/tree
    networks:
      - app-network
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    build:
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${NGINX_SERVER_HOST_HTTP_PORT:-8080}:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/tree
    depends_on:
      - postgres
      - php
    networks:
      - app-network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-tree}
    ports:
      - ${POSTGRES_BACKEND_PORT:-54322}:5432
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - app-network

networks:
  app-network:
    driver: bridge