services:
  php:
    image: php:8.3-fpm
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 5174:5174
    volumes:
      - ./:/var/www/tree
    networks:
      - app-network
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    build:
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/tree
    depends_on:
      - postgres
      - php
    networks:
      - app-network

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 54322:5432
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - app-network

networks:
  app-network:
    driver: bridge