home:
  path: /
  controller: App\Controller\HomeController::index

registration:
  path: /registration
  controller: App\Controller\RegistrationController::index

register:
  path: /register
  controller: App\Api\User::registration

login:
  path: /login
  controller: App\Api\User::login